.\" x-roff document
.do mso man.tmac
.TH gs 1 "July 2017" "gs 0.0.0"
.PP
.SH NAME
gs - painless gist creator
.PP
.SH SYNOPSIS
\fBgs\fP [\fB-pPhv\fP] [\fB-d\fP \fIDESCRIPTION\fP] [\fB-f\fP \fIFILENAME\fP] [\fB-g\fP \fIGITHUB_URL\fP] [\fB-u\fP \fIUSER\fP[:\fIPASSWORD\fP] | \fB-U\fP] [\fIFILES\fP ...] 
.PP
.SH DESCRIPTION
Easy way to create GitHub Gists through the command line.
.PP
.SH OPTIONS
.TP
\fB-d\fP \fIDESCRIPTION\fP
\fRSet Gist description
.PP
.TP
\fB-f\fP \fIFILENAME\fP
\fRSet file name when reading from `\f[CR]stdin\fP'
.PP
.TP
\fB-g\fP \fIGITHUB_URL\fP
\fRChange the GitHub API URL
.PP
.TP
\fB-p
\fRMake Gist private
.PP
.TP
\fB-P
\fRMake Gist public (default)
.PP
.TP
\fB-u\fP \fIUSER\fP[:\fIPASSWORD\fP]
\fRChange the GitHub account the Gist will be posted under. A password can given as well with a separating colon, a prompt is provided if not.
.PP
.TP
\fB-U
\fRPost Gist anonymously (default)
.PP
.TP
\fB-h
\fRPrint help and exit
.PP
.TP
\fB-v
\fRPrint version info and exit
.PP
.SH USAGE
Create a new Gist of file `\f[CR]file.txt\fP':
.PP
.RS 4
.EX

$ gs file.txt
https://gist.github.com/<new-id>

.EE
.RE
.PP
There is also support for multiple files in a single Gist:
.PP
.RS 4
.EX

$ gs README.md Makefile prog.c
https://gist.github.com/<new-id>

.EE
.RE
.PP
Specify the Gist's description:
.PP
.RS 4
.EX

$ gs -d 'a cool shell script' script.sh
https://gist.github.com/<new-id>

.EE
.RE
.PP
The Gist's URL can be piped to other programs, for example to your clipboard to be pasted else where:
.PP
.RS 4
.EX

$ gs file.txt | xsel -bi

.EE
.RE
.PP
You can also create a new Gist from `\f[CR]stdin\fP'. The file name needs to be supplied however:
.PP
.RS 4
.EX

$ cmd-which-errors | gs -f log.txt
https://gist.github.com/<new-id>

.EE
.RE
.PP
New Gists can be private as well:
.PP
.RS 4
.EX

$ gs -p personal.info
https://gist.github.com/<new-id>

.EE
.RE
.PP
The new Gist can be posted under a GitHub user, a prompt will ask for your password:
.PP
.RS 4
.EX

$ gs -u your-name good-proj.rs
GitHub password:
https://gist.github.com/<new-id>

.EE
.RE
.PP
To skip the prompt your password can be supplied after a colon with the username:
.PP
.RS 4
.EX

$ gs -u your-name:password plugin/func.vim doc/func.txt
https://gist.github.com/<new-id>

.EE
.RE
.PP
.SH AUTHOR
Ed van Bruggen <edvb54@gmail.com>
.PP
.SH SEE ALSO
See project page at <http://edryd.org/projects/gs.html>
.PP
View source code at <https://github.com/edvb/gs>
.PP
.SH LICENSE
zlib License
